### ISSUE TITLE
Shipped CLI installation Error

### ISSUE THREAD

**Issue by ghost** [CiscoCloud/shipped-feedback#10]
On executing "curl http://shipped-api.shipped-cisco.com/cli/static/shipped.sh | bash -s" getting following error:
curl http://shipped-api.shipped-cisco.com/cli/static/shipped.sh | bash -s
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    54  100    54    0     0    154      0 --:--:-- --:--:-- --:--:--   155
bash: line 1: a: No such file or directory

**Comment by npateriya** [comment]
Shipped have enabled https endpoint and moved to new domain ciscoshipped.io 

Latest CLI install command in Shipped UI, its updated to
curl https://api.ciscoshipped.io/cli/static/shipped.sh | bash -s

**Comment by ghost** [comment]
Thanks
