### ISSUE TITLE
Spring Buildpack fails out of the box

### ISSUE THREAD

**Issue by tmaoz** [CiscoCloud/shipped-feedback#12]
I created a new project "talco" with a new Spring service "talco1". The bootstrap worked (after some convincing that included installing non standard Ruby and Vagrant versions for my Ubuntu 14.04, as well as VirtualBox, and exporting various environment variables to get vagrant to actually run) but any other builds just fail:

"[ERROR] Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:2.6:resources (default-resources) on project demo: Cannot create resource output directory: /drone/src/github.com/tmaoz/talco1/target/classes -> [Help 1]"

What's going on?
All I did was add the following line to the demo code that was created and pushed:

System.out.println("Hello World!");

Also, it looks like when I took down the VM that was launched, all the build just got stuck. Could it be that builds are always carried out on that local VM? even those that are ment to be deployed to the Cisco cloud? because that would be immensely stupid!

**Comment by mikeihbe** [comment]
Shipped is designed to provide you with a consistent local dev environment.
You don't need to build your application in the VM, but if you do you don't
need all the dependencies installed locally. If you have them anyway, then
you can just develop locally as normal.

Anyway, I'll test this buildpacks today.

On Tuesday, December 22, 2015, tmaoz notifications@github.com wrote:

> I created a new project "talco" with a new Spring service "talco1". The
> bootstrap worked (after some convincing that included installing non
> standard Ruby and Vagrant versions for my Ubuntu 14.04, as well as
> VirtualBox, and exporting various environment variables to get vagrant to
> actually run) but any other builds just fail:
> 
> "[ERROR] Failed to execute goal
> org.apache.maven.plugins:maven-resources-plugin:2.6:resources
> (default-resources) on project demo: Cannot create resource output
> directory: /drone/src/github.com/tmaoz/talco1/target/classes -> [Help 1]"
> 
> What's going on?
> All I did was add the following line to the demo code that was created and
> pushed:
> 
> System.out.println("Hello World!");
> 
> Also, it looks like when I took down the VM that was launched, all the
> build just got stuck. Could it be that builds are always carried out on
> that local VM? even those that are ment to be deployed to the Cisco cloud?
> because that would be immensely stupid!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CiscoCloud/shipped-feedback/issues/12.

## 

Sent from an abacus

**Comment by tmaoz** [comment]
I was just trying out Shipped, I wasn't doing anything special.
I followed the walkthrough in the docs page.
When you create a new project with a new service it creates a GitHub repo for the service and gives you a command-line to installed shipped CLI on your system and then a command to do a bootstrap of your service so you can start developing it. 
I just ran those 2 commands and it failed because it says I had an old vagrant installed.
So I had to upgrade to a non-standard (not the standard Ubuntu 14.04 deb package) vagrant, which, in turn, required me to install ruby 2.0 instead of the ruby I had installed.
After that, the bootstrap was able to complete but when it actually did was create a VirtualBox VM on my machine (luck I had VirtualBox already installed or it would have probably forced me to install that as well) using a docker2boot image Shipped downloaded to my machine, created a docker container in the VM and then proceeded to build and deploy the demo service within that container.

So that seems to have worked. But the that build didn't show up in the "builds" page or via the CLI. and so I pushed new code to initiate a build that I could then deploy, but like I wrote above, the build just fails all the time...

Sorry for the tone, I'm just used to having more control over my builds/services so as an expert developer Shipped makes me feel a bit helpless... (sort of like what a Linux user feels when he/she tries to use Windows, or what a Windows user feels when he/she tries to use OS X ...)

**Comment by mikejihbe** [comment]
I've investigated the reported build failure and I can confirm the issue with this build pack. I'm looking into it, there's probably a misconfiguration in the docker worker nodes preventing the directory from being created, it should be totally fine to do that.

**Comment by mikejihbe** [comment]
It looks like this build image used for this buildpack moves the files into the container as root, but drone doesn't run the build as root, so it can't create the necessary directories. As a workaround, you can add lines like these to your .drone.yml file to get your build to succeed:
https://github.com/mikejihbe/test-spring/blob/master/.drone.yml#L6
https://github.com/mikejihbe/test-spring/blob/master/.drone.yml#L15

This is definitely a bug, we designed this so you can build stuff however you want once you understand the tools. We have a ticket to look into it further.

I would report CLI issues separately, Ubuntu is probably not a thoroughly tested platform within our dev teams.

**Comment by mikejihbe** [comment]
We updated the template repository to fix the permissions when the build runs, see https://github.com/CiscoCloud/shipped-buildpack-template-spring-boot/commit/e241c363b57659d79f225c0c13d0c1404f44a11a.
