### ISSUE TITLE
Bootstrap & Drone errors

### ISSUE THREAD

**Issue by sapientcoffee** [CiscoCloud/shipped-feedback#18]
I am trying to create my 1st example get the following issue with all of the projects I try to create.

The following is output when trying to bootstrap 

```
WARNING 2016/01/22 19:42:46 common.go:82: Unable to repair service rob (1d51c938-0b3b-11e5-9cb4-7cd1c3e98f29) of project rob (f9545cbb-c13e-11e5-8543-0242ac1127ea): Error 503 Service Unavailable - Received error response from Drone
ERROR Bootstrap failed: Unable to bootstrap project rob - a service is not ready:
        Could not enable CI build for service rob (1d51c938-0b3b-11e5-9cb4-7cd1c3e98f29)
      Please review repair options for this project on the Shipped UI
```

The following are the errors I see in the UI. When I select fix error it fails.

<img width="1287" alt="screen shot 2016-01-22 at 19 45 12" src="https://cloud.githubusercontent.com/assets/56030/12521155/c40db5ee-c140-11e5-8e2e-02dbb7b96ad8.png">

<img width="1291" alt="screen shot 2016-01-22 at 19 45 23" src="https://cloud.githubusercontent.com/assets/56030/12521165/ddd999a2-c140-11e5-9411-7f243b3adcdf.png">

One of these projects is here - https://ciscoshipped.io/projects/a40c876b-62ab-11e5-80a2-0242ac113ce8/overview

**Comment by sapientcoffee** [comment]
Is it just my account that is having issues or does everyone have the same issue?

**Comment by patricklmiller** [comment]
I'm getting the same errors as well.

**Comment by lanzafame** [comment]
I am also getting this error. I am using the golang buildpack.

**Comment by mikejihbe** [comment]
Does hitting the repair button fix it for you?

On Sun, Mar 13, 2016 at 9:46 PM, Adrian Lanzafame notifications@github.com
wrote:

> I am also getting this error. I am using the golang buildpack.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CiscoCloud/shipped-feedback/issues/18#issuecomment-196137257
> .

## 

Mike Ihbe
MustWin - Principal

mike@mustwin.com
mikejihbe@gmail.com
skype: mikeihbe
Cell: 651.283.0815

**Comment by patricklmiller** [comment]
No. It can't repair it.
Does hitting the repair button fix it for you?

On Sun, Mar 13, 2016 at 9:46 PM, Adrian Lanzafame notifications@github.com
wrote:

> I am also getting this error. I am using the golang buildpack.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CiscoCloud/shipped-feedback/issues/18#issuecomment-196137257
> .

## 

Mike Ihbe
MustWin - Principal

mike@mustwin.com
mikejihbe@gmail.com
skype: mikeihbe
Cell: 651.283.0815

---

**Comment by mikejihbe** [comment]
We believe this is resolved now, please try again and thanks for reporting your issues!

**Comment by lanzafame** [comment]
Working for me now. Cheers
