### ISSUE TITLE
Failed to deploy required dependency: shipped101helloworld

### ISSUE THREAD

**Issue by eckelcu** [CiscoCloud/shipped-feedback#2]
I am running Learning Lab Shipped 101:
https://learninglabs.cisco.com/lab/shipped-101-first-project/step/3

I successfully created and built a project as described in the learning lab.
![screen shot 2015-08-06 at 3 27 11 pm](https://cloud.githubusercontent.com/assets/6248638/9124847/b19086c4-3c4f-11e5-91e7-6a79de57de72.png)

When I select my build and choose "Deploy", it results in the error "Failed to deploy required dependency: shipped101helloworld"

Clicking on "View Logs" shows "Loading..."

**Comment by mikejihbe** [comment]
I believe this is fixed, reopen if not.
