### ISSUE TITLE
Error in building project -"Timeout expired syncing Drone user"

### ISSUE THREAD

**Issue by jack1001** [CiscoCloud/shipped-feedback#6]
When trying to run build I get the following error
"Timeout expired syncing Drone user"

![build](https://cloud.githubusercontent.com/assets/13464643/10933127/eaad63d4-82de-11e5-8e3e-700672460df7.png)

Might be related to authenticaiton as when I try to login from IE and get error message :URL inaccessible

![image](https://cloud.githubusercontent.com/assets/13464643/10933185/4ce97e8e-82df-11e5-9e53-b2c5b72c88e1.png)

**Comment by mikejihbe** [comment]
We upgraded drone to a newer version, this doesn't happen anymore.
