### ISSUE TITLE
front page ? icon - interface issue

### ISSUE THREAD

**Issue by kmontres** [CiscoCloud/shipped-feedback#7]
In the lower right corner of the initial page is a Question Mark icon- which generally denotes some kind of Help text or FAQs. When I mouse over it, it changes to an "i" icon (italicized), and pops up feedback text.
The expectation is that the icon should remain constant and be consistent with the resulting text pop-up.
Since you also have a Docs link at the top of the page, the Question Mark is not needed. Hopefully, the Docs page will lead you eventually to useful Help text.

**Comment by mikejihbe** [comment]
Fixed on staging and will be deployed later today
