### ISSUE TITLE
my build is stuck for 2 hours now

### ISSUE THREAD

**Issue by muthumayan** [CiscoCloud/shipped-feedback#8]
# 6e072 is the build id.

**Comment by rajcisco** [comment]
On Dec 4, 2015, at 11:53 AM, muthumayan <notifications@github.com<mailto:notifications@github.com>> wrote:

#6e072 is the build id.

##

**Comment by mikejihbe** [comment]
I believe I resolved this with @muthumayan, it had to do with changing API URLs
